// GENERATED by b2b-index-engine stage 08 on 2026-09-01. Do not edit. Source: data/scores.json
import type { Snapshot } from "./b2bindexSnapshotTypes";

export const snapshot: Snapshot = {
  "generatedAt": "2026-09-01T23:41:56.326767+00:00",
  "updatedLabel": "Updated Sep 2026",
  "previousSnapshotDate": null,
  "category": "Digital & AI Marketing",
  "companies": [
    {
      "slug": "kalungi-inc",
      "name": "Kalungi, Inc.",
      "domain": "kalungi.com",
      "blurb": "Kalungi, Inc. is a B2B SaaS growth company",
      "founded": "2018",
      "hq": "Seattle, WA, US",
      "reputation": null,
      "culture": 78,
      "authority": 51,
      "index": 65,
      "indexMath": "(78 + 51) / 2 = 64.5 -> 65, reputation not scored: no review platform passed the identity check",
      "rank": 1,
      "delta": null,
      "why": "Kalungi, Inc. is a B2B SaaS growth company. Its strongest part is employee reviews at 78, and an Index of 65 puts it 1st of 15, with customer reviews still unscored.",
      "sources": [
        {
          "platform": "Glassdoor",
          "href": "https://www.glassdoor.com/Overview/Working-at-Kalungi-EI_IE3908271.11,18.htm"
        },
        {
          "platform": "Indeed",
          "href": "https://www.indeed.com/cmp/Kalungi-Inc."
        },
        {
          "platform": "Company site",
          "href": "https://www.kalungi.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": 78,
          "rows": [
            {
              "label": "Glassdoor",
              "value": "4.0",
              "meta": "28 reviews"
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "65%",
              "muted": false
            },
            {
              "label": "Approve of CEO",
              "value": "92%",
              "muted": false
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture 78 of 100",
          "math": "(28x4.0 + 10x3.7) / (28 + 10) = 3.92 stars, x20 = 78.4; 0.6 x 78.4 + 0.2 x 65 + 0.2 x 92 = 78.45 -> 78"
        },
        "authority": {
          "value": 51,
          "rows": [
            {
              "label": "Domain authority",
              "value": "51",
              "meta": "from a domain rank of 509"
            },
            {
              "label": "Category rank",
              "value": "1st of 15 indexed"
            }
          ],
          "total": "Authority 51 of 100",
          "math": "domain rank 509 / 10 = 50.9 -> 51 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "brew-interactive",
      "name": "Brew Interactive",
      "domain": "brewinteractive.com",
      "blurb": "Brew Interactive is a full-service digital marketing agency founded in 2009",
      "founded": "2009",
      "hq": "Singapore, SG",
      "reputation": 68,
      "culture": 86,
      "authority": 29,
      "index": 61,
      "indexMath": "(68 + 86 + 29) / 3 = 61 -> 61",
      "rank": 2,
      "delta": null,
      "why": "Brew Interactive is a full-service digital marketing agency founded in 2009. Its strongest part is employee reviews at 86, and an Index of 61 puts it 2nd of 15.",
      "sources": [
        {
          "platform": "Google",
          "href": "https://www.google.com/maps/place/?q=place_id:ChIJ05A6QoQZ2jERIpvhoTQLKMg"
        },
        {
          "platform": "Glassdoor",
          "href": "https://www.glassdoor.com/Overview/Working-at-Brew-Interactive-EI_IE4125003.11,27.htm"
        },
        {
          "platform": "Indeed",
          "href": "https://sg.indeed.com/cmp/Brew-Interactive-Pte.-Ltd."
        },
        {
          "platform": "Company site",
          "href": "https://brewinteractive.com/us"
        }
      ],
      "detail": {
        "reputation": {
          "value": 68,
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "4.9",
              "meta": "31 reviews"
            },
            {
              "label": "Recency",
              "value": "Most recent review today",
              "muted": false
            },
            {
              "label": "Spread",
              "value": "Listed on 1 of 3 platforms",
              "muted": false
            }
          ],
          "total": "Reputation 68 of 100",
          "math": "98.0 + 35.0 + 70.8 = 203.8, / 3 = 67.93 -> 68"
        },
        "culture": {
          "value": 86,
          "rows": [
            {
              "label": "Glassdoor",
              "value": "4.3",
              "meta": "14 reviews"
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "100%",
              "muted": false
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture 86 of 100",
          "math": "(14x4.3 + 10x3.7) / (14 + 10) = 4.05 stars, x20 = 81.0; 0.75 x 81.0 + 0.25 x 100 = 85.75 (only would recommend published) -> 86"
        },
        "authority": {
          "value": 29,
          "rows": [
            {
              "label": "Domain authority",
              "value": "29",
              "meta": "from a domain rank of 285"
            },
            {
              "label": "Category rank",
              "value": "6th of 15 indexed"
            }
          ],
          "total": "Authority 29 of 100",
          "math": "domain rank 285 / 10 = 28.5 -> 29 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "ioi-ventures",
      "name": "IOI Ventures",
      "domain": "ioiventures.com",
      "blurb": "IOI Ventures is a plug-and-play marketing arm focused on brand strategy, digital marketing",
      "founded": "2019",
      "hq": "Sarasota, FL, US",
      "reputation": null,
      "culture": 84,
      "authority": 28,
      "index": 56,
      "indexMath": "(84 + 28) / 2 = 56 -> 56, reputation not scored: no review platform passed the identity check",
      "rank": 3,
      "delta": null,
      "why": "IOI Ventures is a plug-and-play marketing arm focused on brand strategy, digital marketing. Its strongest part is employee reviews at 84, and an Index of 56 puts it 3rd of 15, with customer reviews still unscored.",
      "sources": [
        {
          "platform": "Glassdoor",
          "href": "https://www.glassdoor.com/Overview/Working-at-IOI-Ventures-EI_IE4371490.11,23.htm"
        },
        {
          "platform": "Indeed",
          "href": "https://www.indeed.com/cmp/Ioi-Ventures"
        },
        {
          "platform": "Company site",
          "href": "https://www.ioiventures.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": 84,
          "rows": [
            {
              "label": "Glassdoor",
              "value": "4.5",
              "meta": "16 reviews, from the search snippet"
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture 84 of 100",
          "math": "(16x4.5 + 10x3.7) / (16 + 10) = 4.19 stars, x20 = 83.8; 83.8 (no recommend or CEO percentage published, employee rating alone) -> 84"
        },
        "authority": {
          "value": 28,
          "rows": [
            {
              "label": "Domain authority",
              "value": "28",
              "meta": "from a domain rank of 282"
            },
            {
              "label": "Category rank",
              "value": "7th of 15 indexed"
            }
          ],
          "total": "Authority 28 of 100",
          "math": "domain rank 282 / 10 = 28.2 -> 28 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "sculpt",
      "name": "Sculpt",
      "domain": "wearesculpt.com",
      "blurb": "Sculpt is a B2B social media marketing agency founded in 2012",
      "founded": "2012",
      "hq": "Iowa City, IA, US",
      "reputation": 44,
      "culture": 90,
      "authority": 22,
      "index": 52,
      "indexMath": "(44 + 90 + 22) / 3 = 52 -> 52",
      "rank": 4,
      "delta": null,
      "why": "Sculpt is a B2B social media marketing agency founded in 2012. Its strongest part is employee reviews at 90, and an Index of 52 puts it 4th of 15.",
      "sources": [
        {
          "platform": "Clutch",
          "href": "https://clutch.co/profile/sculpt"
        },
        {
          "platform": "Glassdoor",
          "href": "https://www.glassdoor.com/Overview/Working-at-Sculpt-EI_IE874011.11,17.htm"
        },
        {
          "platform": "Company site",
          "href": "https://wearesculpt.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": 44,
          "rows": [
            {
              "label": "Clutch",
              "value": "4.8",
              "meta": "22 reviews"
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "Most recent review about 3 years ago",
              "muted": false
            },
            {
              "label": "Spread",
              "value": "Listed on 1 of 3 platforms",
              "muted": false
            }
          ],
          "total": "Reputation 44 of 100",
          "math": "96.0 + 35.0 + 0.0 = 131.0, / 3 = 43.67 -> 44"
        },
        "culture": {
          "value": 90,
          "rows": [
            {
              "label": "Glassdoor",
              "value": "4.8",
              "meta": "8 reviews"
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "100%",
              "muted": false
            },
            {
              "label": "Approve of CEO",
              "value": "100%",
              "muted": false
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture 90 of 100",
          "math": "(8x4.8 + 10x3.7) / (8 + 10) = 4.19 stars, x20 = 83.8; 0.6 x 83.8 + 0.2 x 100 + 0.2 x 100 = 90.27 -> 90"
        },
        "authority": {
          "value": 22,
          "rows": [
            {
              "label": "Domain authority",
              "value": "22",
              "meta": "from a domain rank of 220"
            },
            {
              "label": "Category rank",
              "value": "10th of 15 indexed"
            }
          ],
          "total": "Authority 22 of 100",
          "math": "domain rank 220 / 10 = 22.0 -> 22 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "lasso-up",
      "name": "Lasso Up",
      "domain": "lasso-up.com",
      "blurb": "Lasso Up is a growth marketing agency built for brands that want momentum, not maintenance",
      "founded": "1999",
      "hq": "Naples, FL, US",
      "reputation": 60,
      "culture": null,
      "authority": 42,
      "index": 51,
      "indexMath": "(60 + 42) / 2 = 51 -> 51, culture not scored: no Glassdoor or Indeed listing found",
      "rank": 5,
      "delta": null,
      "why": "Lasso Up is a growth marketing agency built for brands that want momentum, not maintenance. Its strongest part is customer reviews at 60, and an Index of 51 puts it 5th of 15, with employee reviews still unscored.",
      "sources": [
        {
          "platform": "Google",
          "href": "https://www.google.com/maps/place/?q=place_id:ChIJAQCwGvbj2ogRYxFqXEnp7ME"
        },
        {
          "platform": "Company site",
          "href": "https://lasso-up.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": 60,
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "4.7",
              "meta": "31 reviews"
            },
            {
              "label": "Recency",
              "value": "Most recent review 2 months ago",
              "muted": false
            },
            {
              "label": "Spread",
              "value": "Listed on 1 of 3 platforms",
              "muted": false
            }
          ],
          "total": "Reputation 60 of 100",
          "math": "94.0 + 35.0 + 51.6 = 180.6, / 3 = 60.20 -> 60"
        },
        "culture": {
          "value": null,
          "reason": "No Glassdoor or Indeed listing found.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "No Glassdoor or Indeed listing found."
        },
        "authority": {
          "value": 42,
          "rows": [
            {
              "label": "Domain authority",
              "value": "42",
              "meta": "from a domain rank of 423"
            },
            {
              "label": "Category rank",
              "value": "2nd of 15 indexed"
            }
          ],
          "total": "Authority 42 of 100",
          "math": "domain rank 423 / 10 = 42.3 -> 42 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "market-mentors",
      "name": "Market Mentors",
      "domain": "marketmentors.com",
      "blurb": "Market Mentors is a full-service, fully integrated marketing agency",
      "founded": "2003",
      "hq": "Springfield, MA, US",
      "reputation": null,
      "culture": 68,
      "authority": 30,
      "index": 49,
      "indexMath": "(68 + 30) / 2 = 49 -> 49, reputation not scored: no review platform passed the identity check",
      "rank": 6,
      "delta": null,
      "why": "Market Mentors is a full-service, fully integrated marketing agency. Its strongest part is employee reviews at 68, and an Index of 49 puts it 6th of 15, with customer reviews still unscored.",
      "sources": [
        {
          "platform": "Glassdoor",
          "href": "https://www.glassdoor.com/Overview/Working-at-Market-Mentors-EI_IE3466307.11,25.htm"
        },
        {
          "platform": "Indeed",
          "href": "https://www.indeed.com/cmp/Market-Mentors,-LLC-1"
        },
        {
          "platform": "Company site",
          "href": "https://marketmentors.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": 68,
          "rows": [
            {
              "label": "Glassdoor",
              "value": "3.2",
              "meta": "10 reviews"
            },
            {
              "label": "Indeed",
              "value": "4.2",
              "meta": "5 reviews"
            },
            {
              "label": "Would recommend",
              "value": "57%",
              "muted": false
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture 68 of 100",
          "math": "(10x3.2 + 5x4.2 + 10x3.7) / (15 + 10) = 3.60 stars, x20 = 72.0; 0.75 x 72.0 + 0.25 x 57 = 68.25 (only would recommend published) -> 68"
        },
        "authority": {
          "value": 30,
          "rows": [
            {
              "label": "Domain authority",
              "value": "30",
              "meta": "from a domain rank of 300"
            },
            {
              "label": "Category rank",
              "value": "5th of 15 indexed"
            }
          ],
          "total": "Authority 30 of 100",
          "math": "domain rank 300 / 10 = 30.0 -> 30 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "thought-lab",
      "name": "ThoughtLab",
      "domain": "thoughtlab.com",
      "blurb": "ThoughtLab is a category-first brand and product studio that helps organizations at pivotal growth moments",
      "founded": "1999",
      "hq": "Salt Lake City, UT, US",
      "reputation": null,
      "culture": 67,
      "authority": 28,
      "index": 48,
      "indexMath": "(67 + 28) / 2 = 47.5 -> 48, reputation not scored: no review platform passed the identity check",
      "rank": 7,
      "delta": null,
      "why": "ThoughtLab is a category-first brand and product studio that helps organizations at pivotal growth moments. Its strongest part is employee reviews at 67, and an Index of 48 puts it 7th of 15, with customer reviews still unscored.",
      "sources": [
        {
          "platform": "Glassdoor",
          "href": "https://www.glassdoor.com/Overview/Working-at-ThoughtLab-EI_IE322343.11,21.htm"
        },
        {
          "platform": "Indeed",
          "href": "https://www.indeed.com/cmp/Thoughtlab"
        },
        {
          "platform": "Company site",
          "href": "https://www.thoughtlab.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": 67,
          "rows": [
            {
              "label": "Glassdoor",
              "value": "3.4",
              "meta": "16 reviews"
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "62%",
              "muted": false
            },
            {
              "label": "Approve of CEO",
              "value": "64%",
              "muted": false
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture 67 of 100",
          "math": "(16x3.4 + 10x3.7) / (16 + 10) = 3.52 stars, x20 = 70.3; 0.6 x 70.3 + 0.2 x 62 + 0.2 x 64 = 67.38 -> 67"
        },
        "authority": {
          "value": 28,
          "rows": [
            {
              "label": "Domain authority",
              "value": "28",
              "meta": "from a domain rank of 281"
            },
            {
              "label": "Category rank",
              "value": "8th of 15 indexed"
            }
          ],
          "total": "Authority 28 of 100",
          "math": "domain rank 281 / 10 = 28.1 -> 28 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "inbound-av",
      "name": "InboundAV",
      "domain": "inboundav.com",
      "blurb": "InboundAV is an award-winning, AI-first business development and digital marketing agency based in Los Angeles",
      "founded": "2017",
      "hq": "Glendale, CA, US",
      "reputation": null,
      "culture": null,
      "authority": 35,
      "index": 35,
      "indexMath": "(35) / 1 = 35 -> 35, reputation not scored: no review platform passed the identity check, culture not scored: no Glassdoor or Indeed listing found",
      "rank": 8,
      "delta": null,
      "why": "InboundAV is an award-winning, AI-first business development and digital marketing agency based in Los Angeles. Its strongest part is domain authority at 35, and an Index of 35 puts it 8th of 15, with customer reviews and employee reviews still unscored.",
      "sources": [
        {
          "platform": "Company site",
          "href": "https://www.inboundav.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": null,
          "reason": "No Glassdoor or Indeed listing found.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "No Glassdoor or Indeed listing found."
        },
        "authority": {
          "value": 35,
          "rows": [
            {
              "label": "Domain authority",
              "value": "35",
              "meta": "from a domain rank of 347"
            },
            {
              "label": "Category rank",
              "value": "3rd of 15 indexed"
            }
          ],
          "total": "Authority 35 of 100",
          "math": "domain rank 347 / 10 = 34.7 -> 35 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "human-code",
      "name": "Human_Code",
      "domain": "humancode.ca",
      "blurb": "Human_Code is a growth consultancy that helps businesses align teams, systems, and strategies",
      "founded": "2001",
      "hq": "Hamilton, ON, CA",
      "reputation": null,
      "culture": null,
      "authority": 32,
      "index": 32,
      "indexMath": "(32) / 1 = 32 -> 32, reputation not scored: no review platform passed the identity check, culture not scored: no Glassdoor or Indeed listing found",
      "rank": 9,
      "delta": null,
      "why": "Human_Code is a growth consultancy that helps businesses align teams, systems, and strategies. Its strongest part is domain authority at 32, and an Index of 32 puts it 9th of 15, with customer reviews and employee reviews still unscored.",
      "sources": [
        {
          "platform": "Company site",
          "href": "https://humancode.ca/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": null,
          "reason": "No Glassdoor or Indeed listing found.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "No Glassdoor or Indeed listing found."
        },
        "authority": {
          "value": 32,
          "rows": [
            {
              "label": "Domain authority",
              "value": "32",
              "meta": "from a domain rank of 315"
            },
            {
              "label": "Category rank",
              "value": "4th of 15 indexed"
            }
          ],
          "total": "Authority 32 of 100",
          "math": "domain rank 315 / 10 = 31.5 -> 32 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "markezing",
      "name": "Markezing",
      "domain": "markezing.com",
      "blurb": "Smart RevOps & HubSpot gurus for businesses in New Zealand and Australia, specialized in revenue operations",
      "founded": "2012",
      "hq": "Pukekohe, Auckland, NZ",
      "reputation": null,
      "culture": null,
      "authority": 27,
      "index": 27,
      "indexMath": "(27) / 1 = 27 -> 27, reputation not scored: only 2 reviews across all platforms, fewer than the 5 needed to score, culture not scored: no Glassdoor or Indeed listing found",
      "rank": 10,
      "delta": null,
      "why": "Markezing is smart RevOps & HubSpot gurus for businesses in New Zealand and Australia, specialized in revenue operations. Its strongest part is domain authority at 27, and an Index of 27 puts it 10th of 15, with customer reviews and employee reviews still unscored.",
      "sources": [
        {
          "platform": "Google",
          "href": "https://www.google.com/maps/place/?q=place_id:ChIJRdLPB9GrEm0RCImVh3ugaNM"
        },
        {
          "platform": "Company site",
          "href": "https://www.markezing.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "Only 2 reviews across all platforms, fewer than the 5 needed to score.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "5",
              "meta": "2 reviews"
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 1 of 3 platforms",
              "muted": false
            }
          ],
          "total": "Reputation not scored yet",
          "math": "Only 2 reviews across all platforms, fewer than the 5 needed to score."
        },
        "culture": {
          "value": null,
          "reason": "No Glassdoor or Indeed listing found.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "No Glassdoor or Indeed listing found."
        },
        "authority": {
          "value": 27,
          "rows": [
            {
              "label": "Domain authority",
              "value": "27",
              "meta": "from a domain rank of 266"
            },
            {
              "label": "Category rank",
              "value": "9th of 15 indexed"
            }
          ],
          "total": "Authority 27 of 100",
          "math": "domain rank 266 / 10 = 26.6 -> 27 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "discover-digital",
      "name": "Discover Digital",
      "domain": "discoverdigital.com",
      "blurb": "Discover Digital is an award-winning digital agency specializing in digital transformation",
      "founded": "1993",
      "hq": "Reading, Berkshire, GB",
      "reputation": null,
      "culture": null,
      "authority": 22,
      "index": 22,
      "indexMath": "(22) / 1 = 22 -> 22, reputation not scored: only 2 reviews across all platforms, fewer than the 5 needed to score, culture not scored: only 1 employee rating, fewer than the 5 needed to score",
      "rank": 11,
      "delta": null,
      "why": "Discover Digital is an award-winning digital agency specializing in digital transformation. Its strongest part is domain authority at 22, and an Index of 22 puts it 11th of 15, with customer reviews and employee reviews still unscored.",
      "sources": [
        {
          "platform": "Google",
          "href": "https://www.google.com/maps/place/?q=place_id:ChIJMYR6lRyidkgRr2f8AQhQSkY"
        },
        {
          "platform": "Glassdoor",
          "href": "https://www.glassdoor.com/Overview/Working-at-Discover-Digital-EI_IE10812368.11,27.htm"
        },
        {
          "platform": "Indeed",
          "href": "https://za.indeed.com/cmp/Discover-Digital"
        },
        {
          "platform": "Company site",
          "href": "https://discoverdigital.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "Only 2 reviews across all platforms, fewer than the 5 needed to score.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "5",
              "meta": "2 reviews"
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 1 of 3 platforms",
              "muted": false
            }
          ],
          "total": "Reputation not scored yet",
          "math": "Only 2 reviews across all platforms, fewer than the 5 needed to score."
        },
        "culture": {
          "value": null,
          "reason": "Only 1 employee rating, fewer than the 5 needed to score.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "5.0",
              "meta": "1 review"
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "Only 1 employee rating, fewer than the 5 needed to score."
        },
        "authority": {
          "value": 22,
          "rows": [
            {
              "label": "Domain authority",
              "value": "22",
              "meta": "from a domain rank of 219"
            },
            {
              "label": "Category rank",
              "value": "11th of 15 indexed"
            }
          ],
          "total": "Authority 22 of 100",
          "math": "domain rank 219 / 10 = 21.9 -> 22 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "twenty-first-digital",
      "name": "Twenty-First Digital",
      "domain": "twentyfirstdigital.com",
      "blurb": "Twenty-First Digital is an audience development agency",
      "founded": "2018",
      "hq": "Flower Mound, TX, US",
      "reputation": null,
      "culture": null,
      "authority": 16,
      "index": 16,
      "indexMath": "(16) / 1 = 16 -> 16, reputation not scored: no review platform passed the identity check, culture not scored: only 3 employee ratings, fewer than the 5 needed to score",
      "rank": 12,
      "delta": null,
      "why": "Twenty-First Digital is an audience development agency. Its strongest part is domain authority at 16, and an Index of 16 puts it 12th of 15, with customer reviews and employee reviews still unscored.",
      "sources": [
        {
          "platform": "Glassdoor",
          "href": "https://www.glassdoor.com/Overview/Working-at-Twenty-First-Digital-EI_IE3243293.11,31.htm"
        },
        {
          "platform": "Company site",
          "href": "https://www.twentyfirstdigital.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": null,
          "reason": "Only 3 employee ratings, fewer than the 5 needed to score.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "5.0",
              "meta": "3 reviews"
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "Only 3 employee ratings, fewer than the 5 needed to score."
        },
        "authority": {
          "value": 16,
          "rows": [
            {
              "label": "Domain authority",
              "value": "16",
              "meta": "from a domain rank of 161"
            },
            {
              "label": "Category rank",
              "value": "12th of 15 indexed"
            }
          ],
          "total": "Authority 16 of 100",
          "math": "domain rank 161 / 10 = 16.1 -> 16 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "nektur",
      "name": "Nektur",
      "domain": "nektur.com",
      "blurb": "Nektur bridges the HubSpot onboarding gap for cost-conscious SMBs and teams who want hands-on control",
      "founded": "2022",
      "hq": "Chattanooga, TN, US",
      "reputation": null,
      "culture": null,
      "authority": 14,
      "index": 14,
      "indexMath": "(14) / 1 = 14 -> 14, reputation not scored: no review platform passed the identity check, culture not scored: no Glassdoor or Indeed listing found",
      "rank": 13,
      "delta": null,
      "why": "Nektur bridges the HubSpot onboarding gap for cost-conscious SMBs and teams who want hands-on control. Its strongest part is domain authority at 14, and an Index of 14 puts it 13th of 15, with customer reviews and employee reviews still unscored.",
      "sources": [
        {
          "platform": "Company site",
          "href": "https://nektur.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": null,
          "reason": "No Glassdoor or Indeed listing found.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "No Glassdoor or Indeed listing found."
        },
        "authority": {
          "value": 14,
          "rows": [
            {
              "label": "Domain authority",
              "value": "14",
              "meta": "from a domain rank of 137"
            },
            {
              "label": "Category rank",
              "value": "13th of 15 indexed"
            }
          ],
          "total": "Authority 14 of 100",
          "math": "domain rank 137 / 10 = 13.7 -> 14 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "addax-lab",
      "name": "Addax Lab",
      "domain": "addaxlab.com",
      "blurb": "AddaxLab is a full-cycle development company specializing in Salesforce, HubSpot, Odoo",
      "founded": "2012",
      "hq": "Ridgewood, NJ, US",
      "reputation": null,
      "culture": null,
      "authority": 13,
      "index": 13,
      "indexMath": "(13) / 1 = 13 -> 13, reputation not scored: no review platform passed the identity check, culture not scored: no Glassdoor or Indeed listing found",
      "rank": 14,
      "delta": null,
      "why": "AddaxLab is a full-cycle development company specializing in Salesforce, HubSpot, Odoo. Its strongest part is domain authority at 13, and an Index of 13 puts it 14th of 15, with customer reviews and employee reviews still unscored.",
      "sources": [
        {
          "platform": "Company site",
          "href": "https://addaxlab.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": null,
          "reason": "No Glassdoor or Indeed listing found.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "No Glassdoor or Indeed listing found."
        },
        "authority": {
          "value": 13,
          "rows": [
            {
              "label": "Domain authority",
              "value": "13",
              "meta": "from a domain rank of 127"
            },
            {
              "label": "Category rank",
              "value": "14th of 15 indexed"
            }
          ],
          "total": "Authority 13 of 100",
          "math": "domain rank 127 / 10 = 12.7 -> 13 (clamped to 1-100)"
        }
      }
    },
    {
      "slug": "rainier-rev-ops",
      "name": "Rainier RevOps",
      "domain": "rainierdigital.com",
      "blurb": "Rainier RevOps helps staffing and recruiting firms, and purpose-driven organizations",
      "founded": "2009",
      "hq": "Liberty Lake, WA, US",
      "reputation": null,
      "culture": null,
      "authority": 10,
      "index": 10,
      "indexMath": "(10) / 1 = 10 -> 10, reputation not scored: no review platform passed the identity check, culture not scored: no Glassdoor or Indeed listing found",
      "rank": 15,
      "delta": null,
      "why": "Rainier RevOps helps staffing and recruiting firms, and purpose-driven organizations. Its strongest part is domain authority at 10, and an Index of 10 puts it 15th of 15, with customer reviews and employee reviews still unscored.",
      "sources": [
        {
          "platform": "Company site",
          "href": "https://www.rainierdigital.com/"
        }
      ],
      "detail": {
        "reputation": {
          "value": null,
          "reason": "No review platform passed the identity check.",
          "rows": [
            {
              "label": "Clutch",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Trustpilot",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Google",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Recency",
              "value": "No dated reviews read",
              "muted": true
            },
            {
              "label": "Spread",
              "value": "Listed on 0 of 3 platforms",
              "muted": true
            }
          ],
          "total": "Reputation not scored yet",
          "math": "No review platform passed the identity check."
        },
        "culture": {
          "value": null,
          "reason": "No Glassdoor or Indeed listing found.",
          "rows": [
            {
              "label": "Glassdoor",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Indeed",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Would recommend",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Approve of CEO",
              "value": "No data yet",
              "muted": true
            },
            {
              "label": "Update schedule",
              "value": "Refreshed quarterly"
            }
          ],
          "total": "Culture not scored yet",
          "math": "No Glassdoor or Indeed listing found."
        },
        "authority": {
          "value": 10,
          "rows": [
            {
              "label": "Domain authority",
              "value": "10",
              "meta": "from a domain rank of 95"
            },
            {
              "label": "Category rank",
              "value": "15th of 15 indexed"
            }
          ],
          "total": "Authority 10 of 100",
          "math": "domain rank 95 / 10 = 9.5 -> 10 (clamped to 1-100)"
        }
      }
    }
  ],
  "categoryAverages": {
    "reputation": 57,
    "culture": 79,
    "authority": 27,
    "index": 37
  }
};
